# Шаг 1: Берем легкий образ Node.js
FROM node:20-alpine

# --- ИСПРАВЛЕНИЕ: Устанавливаем OpenSSL для Prisma ---
RUN apk add --no-cache openssl

# Шаг 2: Указываем рабочую папку внутри контейнера
WORKDIR /app

# Шаг 3: Копируем файлы зависимостей
COPY package*.json ./

# Шаг 4: Устанавливаем зависимости
RUN npm install

# Шаг 5: Копируем весь остальной код проекта
COPY . .

# Шаг 6: Генерируем Prisma Client
RUN npx prisma generate

# Шаг 7: Открываем порт
EXPOSE 4000

# Шаг 8: Запускаем
CMD ["npm", "run", "dev"]